### ISSUE TITLE
multiple_child_class_id extractor parents

### ISSUE THREAD

**Issue by omacesc** [omatech/editora-extractor#1]
Bones!

Hem detectat amb el Javi que quan volies extreure els pares d'uan relació donaba error, ja que no miraba els fills de multiple_child_class_id. S'hauria de cambiar la sql de la funció 'getRelations' del arxiu EditoraData.php (Linea: 569)

where ( r.child_class_id = $class_id OR FIND_IN_SET( $class_id, r.multiple_child_class_id ) )

**Comment by aponscat** [comment]
tete, tu mateix!!!
clone, commit i push i despres ja podras fer composer upfate. diga-li al alvaro tambe.
I jo quan arribi m'actualitzo.
Merciiiii

Enviado desde mi Apple Watch

On Thu, Jul 7, 2016 at 12:23 PM +0200, "Francesc Delgado" notifications@github.com wrote:

Bones!

Hem detectat amb el Javi que quan volies extreure els pares d'uan relació donaba error, ja que no miraba els fills de multiple_child_class_id. S'hauria de cambiar la sql de la funció 'getRelations' del arxiu EditoraData.php (Linea: 569)

where ( r.child_class_id = $class_id OR FIND_IN_SET( $class_id, r.multiple_child_class_id ) )

**Comment by omacesc** [comment]
Hem sembla que hi ha un altre bug, que es que només treu fills o pares i no
els dos si es una instancia que te pares i fills.
Ho parlem dilluns!

## 

Cesc Delgado
www.omatech.com

On 7 July 2016 at 12:49:27, aponscat (notifications@github.com) wrote:

tete, tu mateix!!!
clone, commit i push i despres ja podras fer composer upfate. diga-li al
alvaro tambe.
I jo quan arribi m'actualitzo.
Merciiiii

Enviado desde mi Apple Watch

On Thu, Jul 7, 2016 at 12:23 PM +0200, "Francesc Delgado" <
notifications@github.com> wrote:

Bones!

Hem detectat amb el Javi que quan volies extreure els pares d'uan relació
donaba error, ja que no miraba els fills de multiple_child_class_id.
S'hauria de cambiar la sql de la funció 'getRelations' del arxiu
EditoraData.php (Linea: 569)

where ( r.child_class_id = $class_id OR FIND_IN_SET( $class_id,
r.multiple_child_class_id ) )

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/omatech/editora-extractor/issues/1#issuecomment-231045472,
or mute the thread
https://github.com/notifications/unsubscribe/AB3BC_tmfKu91ELMYwu7XSbFyhSS90pbks5qTNmngaJpZM4JG8Pf
.

**Comment by aponscat** [comment]
entraria en un bucle infinit, no?

Enviado desde mi Apple Watch

On Fri, Jul 8, 2016 at 5:06 PM +0200, "Francesc Delgado" notifications@github.com wrote:

Hem sembla que hi ha un altre bug, que es que només treu fills o pares i no

els dos si es una instancia que te pares i fills.

Ho parlem dilluns!

## 

Cesc Delgado

www.omatech.com

On 7 July 2016 at 12:49:27, aponscat (notifications@github.com) wrote:

tete, tu mateix!!!

clone, commit i push i despres ja podras fer composer upfate. diga-li al

alvaro tambe.

I jo quan arribi m'actualitzo.

Merciiiii

Enviado desde mi Apple Watch

On Thu, Jul 7, 2016 at 12:23 PM +0200, "Francesc Delgado" <

notifications@github.com> wrote:

Bones!

Hem detectat amb el Javi que quan volies extreure els pares d'uan relació

donaba error, ja que no miraba els fills de multiple_child_class_id.

S'hauria de cambiar la sql de la funció 'getRelations' del arxiu

EditoraData.php (Linea: 569)

where ( r.child_class_id = $class_id OR FIND_IN_SET( $class_id,

r.multiple_child_class_id ) )

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub

https://github.com/omatech/editora-extractor/issues/1#issuecomment-231045472,

or mute the thread

https://github.com/notifications/unsubscribe/AB3BC_tmfKu91ELMYwu7XSbFyhSS90pbks5qTNmngaJpZM4JG8Pf

.
